### PR TITLE
Fix setting of cicp values in avifgainmaputil combine and convert.

### LINKED ISSUE #3102: `avifgainmaputil` color differs from `avifenc`
im having an issue where gainmaps generated with `avifgainmaputil` seem to be shifted toward red in some areas vs `avifenc`; it happens in both a chromium based browser and [tev](https://github.com/Tom94/tev), it's more obvious in HDR but it's still visible in SDR on stuff like the yellow bushes and the grass in the bottom left

---
outside3-v1-sdr-1-13-1-noicc.avif
SDR
=========
```
-> avifenc -d 12 -q 100 --qalpha 100 -y 444 --range full --cicp 1/13/1 --ignore-profile .\outside3-v1-sdr.png .\outside3-v1-sdr-1-13-1-noicc.avif
Successfully loaded: .\outside3-v1-sdr.png
Quality set to 100, assuming --lossless to enable warnings on potential lossless issues.
WARNING: [--lossless] Input data was RGB and matrixCoefficients isn't set to identity (--cicp x/x/0) or YCgCo-Re/Ro (--cicp x/x/16 or x/x/17); Output might not be lossless.
AVIF to be written: (Lossy)
 * Resolution     : 4064x3044
 * Bit Depth      : 12
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 1
 * ICC Profile    : Absent
 * XMP Metadata   : Present (868 bytes)
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
 * Gain map       : Absent
Encoding with initial settings: codec 'aom' speed [6], color quality [100 (Lossless)], alpha quality [100 (Lossless)], automatic tiling, 32 worker thread(s), please wait...
Encoded successfully.
 * Color total size: 29383256 bytes
 * Alpha total size: 0 bytes
Wrote AVIF: .\outside3-v1-sdr-1-13-1-noicc.avif
```
---
outside3-v1-hdr-9-16-9-noicc.avif
HDR
=========
```
-> avifenc -d 12 -q 100 --qalpha 100 -y 444 --range full --cicp 9/16/9 --ignore-profile .\outside3-v1-hdr.png .\outside3-v1-hdr-9-16-9-noicc.avif
libpng warning: iCCP: profile 'Rec. 2020 PQ': 0h: PCS illuminant is not D50
Successfully loaded: .\outside3-v1-hdr.png
Quality set to 100, assuming --lossless to enable warnings on potential lossless issues.
WARNING: [--lossless] Input data was RGB and matrixCoefficients isn't set to identity (--cicp x/x/0) or YCgCo-Re/Ro (--cicp x/x/16 or x/x/17); Output might not be lossless.
AVIF to be written: (Lossy)
 * Resolution     : 4064x3044
 * Bit Depth      : 12
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 9
 * Transfer Char. : 16
 * Matrix Coeffs. : 9
 * ICC Profile    : Absent
 * XMP Metadata   : Present (1243 bytes)
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
 * Gain map       : Absent
Encoding with initial settings: codec 'aom' speed [6], color quality [100 (Lossless)], alpha quality [100 (Lossless)], automatic tiling, 32 worker thread(s), please wait...
Encoded successfully.
 * Color total size: 17976031 bytes
 * Alpha total size: 0 bytes
Wrote AVIF: .\outside3-v1-hdr-9-16-9-noicc.avif
```
---
outside3-v1-gainmap_1-13-1__9-16-9.avif
gainmap
=========
```
-> avifgainmaputil combine `
>     .\outside3-v1-sdr.png `
>     .\outside3-v1-hdr.png `
>     .\outside3-v1-gainmap_1-13-1__9-16-9.avif `
>     -d 12 `
>     -q 100 `
>     --qalpha 100 `
>     -y 444 `
>     --depth-gain-map 12 `
>     --qgain-map 100 `
>     --cicp-base "1/13/1" `
>     --cicp-alternate "9/16/9" `
>     --ignore-profile
libpng warning: iCCP: profile 'Rec. 2020 PQ': 0h: PCS illuminant is not D50
Creating a gain map of size 4064 x 3044
AVIF to be written:
 * Resolution     : 4064x3044
 * Bit Depth      : 12
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 1
 * ICC Profile    : Absent
 * XMP Metadata   : Present (868 bytes)
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
 * Gain map       : 4064x3044 pixels, 12 bit, YUV444, Full Range, Matrix Coeffs. 2, Base Image is SDR
 * Alternate image:
    * Color Primaries: 9
    * Transfer Char. : 16
    * Matrix Coeffs. : 9
    * ICC Profile    : Absent
    * Bit Depth      : 12
    * Planes         : 3

Encoding AVIF at quality 100 speed 6, please wait...
Wrote AVIF: .\outside3-v1-gainmap_1-13-1__9-16-9.avif
```

---

```
-> avifgainmaputil
Command name missing

Experimental tool to manipulate avif images with HDR gain maps.

usage: avifgainmaputil <command> [options] [arguments...]

Available commands:
  help            Prints a command's usage
  combine         Creates an avif image with a gain map from a base image and an alternate image.
  convert         Convert a jpeg with a gain map to avif.
  tonemap         Tone maps an avif image that has a gain map to a given HDR headroom (how much brighter the display can go compared to an SDR display)
  swapbase        Swaps the base and alternate images (e.g. if the base image is SDR and the alternate is HDR, makes the base HDR). The alternate image is the result of fully applying the gain map.
  extractgainmap  Saves the gain map of an avif file as an image
  printmetadata   Prints the metadata of the gain map of an avif file

Version: 1.3.0 (dav1d [dec]:1.5.1-0-g42b2b24, aom [enc]:3.12.1)
libyuv : available (1909)
```

```
-> avifenc --version
Version: 1.3.0 (dav1d [dec]:1.5.1-0-g42b2b24, aom [enc]:3.12.1)
libyuv : available (1909)
```

### PR DESCRIPTION
**Pull request by maryla-uc**
CICP must be set *before* calling ReadImage() so that the RGB->YUV conversion uses the right matrix coefficient for PNG/JPEG files. Also explicitly set the default matrix coefficients when not specified.

For Avif files, we overwrite the CICP after reading the file in ReadImage() (keeps the previous behavior).

Fix --cicp-input flag not being used in tonemap command.

Fix memory leak when in 'combine' command when using with a file that already has a gain map. Fix memory leak in 'tonemap' and 'swapbase' command with RGB pixels.

Fixes #3102 and #2869

### CODE REVIEW

File: apps/avifgainmaputil/combine_command.cc [hunk 1]
```diff
@@ -129,6 +129,9 @@ avifResult CombineCommand::Run() {
   std::cout << "Creating a gain map of size " << gain_map_width << " x "
             << gain_map_height << "\n";
 
+  // Because base_image is read with ignore_gain_map=true, there is no
+  // preexisting gain map. Otherwise, overwriting the pointer would cause a
+  // memory leak.
```
Comment (wantehchang) [inline apps/avifgainmaputil/combine_command.cc:135]: Please add a changelog entry for this PR if appropriate.

Comment (y-guyon) [inline apps/avifgainmaputil/combine_command.cc:135]:
```c
assert(base_image->gainMap == nullptr);
```

File: tests/data/README.md [hunk 2]
```diff
@@ -823,6 +823,19 @@ after changing `kUpdateTestImages` to true in the `avifgainmaptest.cc`.
 
 SDR image with a gain map to allow tone mapping to HDR. The gain map's width and height are halved compared to the base image.
 
+### File [seine_sdr_gainmap_srgb_icc.jpg](seine_sdr_gainmap_srgb_icc.jpg)
+
+![](seine_sdr_gainmap_srgb_icc.jpg)
+
+License: [same as libavif](https://github.com/AOMediaCodec/libavif/blob/main/LICENSE)
+
+Source : created by running the following command with avifenc with compiled with libxml enabled:
```
Comment (y-guyon) [inline tests/data/README.md]: Extra "with"

File: tests/data/README.md [hunk 3]
```diff
@@ -823,6 +823,19 @@ after changing `kUpdateTestImages` to true in the `avifgainmaptest.cc`.
...
+
+```bash
+# from libavif/mybuilddir/
+./avifenc ../tests/data/seine_sdr_gainmap_srgb.jpg ../tests/data/seine_sdr_gainmap_srgb_icc.jpg --qcolor 90 --qgain-map 90
```
Comment (y-guyon) [inline tests/data/README.md]: Simplification suggestion:

```sh
avifenc seine_sdr_gainmap_srgb.jpg seine_sdr_gainmap_srgb_icc.jpg --qcolor 90 --qgain-map 90
```

File: tests/CMakeLists.txt [hunk 4]
```diff
@@ -267,10 +267,9 @@ if(AVIF_BUILD_APPS)
     add_cmd_test(test_cmd_stdin ${CMAKE_CURRENT_SOURCE_DIR}/data)
     add_cmd_test(test_cmd_targetsize ${CMAKE_CURRENT_SOURCE_DIR}/data)
     add_cmd_test(test_cmd_transform ${CMAKE_CURRENT_SOURCE_DIR}/data)
+    add_cmd_test(test_cmd_avifgainmaputil ${CMAKE_CURRENT_SOURCE_DIR}/data)
```
Comment (y-guyon) [inline tests/CMakeLists.txt:270]: Is `avifgainmaputil` built by default?

File: tests/test_cmd_avifgainmaputil.sh [hunk 5]
```diff
@@ -15,26 +15,22 @@ fi
...
 AVIF_OUTPUT="avif_test_cmd_avifgainmaputil_output.avif"
 JPEG_OUTPUT="avif_test_cmd_avifgainmaputil_output.jpg"
 PNG_OUTPUT="avif_test_cmd_avifgainmaputil_output.png"
 
 # Cleanup
 cleanup() {
-  pushd ${TMP_DIR}
-    rm -- "${AVIF_OUTPUT}" "${JPEG_OUTPUT}" "${PNG_OUTPUT}" "${AVIF_GAINMAP_SDR_WITH_ICC}"
-  popd
+  rm -f -r "${TMP_DIR}"
```
Comment (y-guyon) [inline tests/test_cmd_avifgainmaputil.sh:28]: Please keep explicit file deletion. This deletes the whole `/tmp` directory whenever this test exits, right?

File: tests/test_cmd_avifgainmaputil.sh [hunk 6]
```diff
@@ -58,20 +54,50 @@ pushd ${TMP_DIR}
...
+  "${ARE_IMAGES_EQUAL}" "${AVIF_OUTPUT}.tonemapped.png" "input_avif_hdr2020.png" 0 90
+
   "${AVIFGAINMAPUTIL}" swapbase "${INPUT_AVIF_GAINMAP_SDR}" "${AVIF_OUTPUT}" --qcolor 90 --qgain-map 90
   # should fail because icc profiles are not supported
   "${AVIFGAINMAPUTIL}" swapbase "${AVIF_GAINMAP_SDR_WITH_ICC}" "${AVIF_OUTPUT}" --qcolor 90 --qgain-map 90 && exit 1
   "${AVIFGAINMAPUTIL}" swapbase "${AVIF_GAINMAP_SDR_WITH_ICC}" "${AVIF_OUTPUT}" --qcolor 90 --qgain-map 90 --ignore-profile
 
+   # also test the are_images_equal binary itself with some gain maps
+  "${ARE_IMAGES_EQUAL}" "${INPUT_JPEG_AVIF_GAINMAP_SDR}" "${INPUT_JPEG_AVIF_GAINMAP_SDR}" 0 40 0
+  "${ARE_IMAGES_EQUAL}" "${INPUT_JPEG_AVIF_GAINMAP_SDR}" "${INPUT_JPEG_AVIF_GAINMAP_SDR}" 0 40 1
```
Comment (y-guyon) [inline tests/test_cmd_avifgainmaputil.sh]: Optional: Add a negative test for `ARE_IMAGES_EQUAL`

File: tests/CMakeLists.txt (hunk 4 above)
Comment (maryla-uc) [reply tests/CMakeLists.txt:270]: Yes, it's built it the other apps are built

File: tests/test_cmd_avifgainmaputil.sh (hunk 6 above)
Comment (maryla-uc) [reply tests/test_cmd_avifgainmaputil.sh]: Will do in another change. Turns out it doesn't compare the gain map metadata.

File: tests/test_cmd_avifgainmaputil.sh (hunk 5 above)
Comment (maryla-uc) [reply tests/test_cmd_avifgainmaputil.sh:28]: No, it deletes this test's temp dir.  https://github.com/AOMediaCodec/libavif/blob/70fabb41f223d3c2a3f2b06eee33e9a84c675479/tests/cmd_test_common.sh#L38-L42

Either it's a new temp dir, or it's passed on the command line. The latter case is used in google3 (and I'm already deleting all of it in test_cmd_transform.sh and it's not causing issues). If we're worried about deleting the whole directory passed by the user we could create a subdir inside it in cmd_test_common.sh, but tracking every single test file to delete is a pain IMO.
